name: âš—ï¸ Create Ci Environment
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
 build:
    name: 'ğŸ› ï¸ Build'
    uses: equinor/spine-splinter/.github/workflows/build.yml@main

  deploy_to_ci_env:
    name: "ğŸ§ªğŸš€ Deploy to CI environment"
    needs: [build]
    permissions:
      id-token: write
      contents: read
    uses: equinor/spine-splinter/.github/workflows/deploy.yml@main
    with:
      env: 'ci'
      ARTIFACT: ${{ needs.build.outputs.artifact-name }}
      SKU: 'B1'
      buildid: 'ci'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
      FUNC_PUBLISH_PROFILE: ${{ secrets.FUNC_PUBLISH_PROFILE }}


